# Generated by Django 5.1.4 on 2024-12-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tour_food_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
